name: Sync Specific Files from Main to Docs

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

permissions:
  contents: write

jobs:
  sync_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Fetch and checkout docs branch
        run: |
          git fetch origin
          git checkout docs

      - name: Copy lab files from main to docs
        run: |
          git checkout main -- <path_to_lab_files>  # Replace <path_to_lab_files> with actual directories or files to sync

      - name: Restore docs-specific files to ensure they are not overwritten
        run: |
          git restore --source=docs .github/workflows/ci.yml
          git restore --source=docs mkdocs.yml
          git restore --source=docs docs/

      - name: Commit and push changes to docs
        run: |
          git commit -m "Sync lab files from main to docs"
          git push origin docs
