name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material nbconvert

      - name: Generate documentation
        run: |
          if [ -f "generate_docs.py" ]; then
            python generate_docs.py
          else
            echo "generate_docs.py not found"
          fi

      - name: Debug information
        run: |
          echo "Content of mkdocs.yml after generation:"
          cat mkdocs.yml
          echo "\nSearching for 'searchnav' references:"
          grep -R "searchnav" .

      - run: mkdocs gh-deploy --force

  sync_docs:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git credentials for pushing to docs branch
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Merge main branch into docs
        run: |
          git fetch origin
          git checkout docs
          git merge origin/main --no-edit

      - name: Push changes to docs branch
        run: git push origin docs
