name: Sync Specific Files from Main to Docs

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

permissions:
  contents: write

jobs:
  sync_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Fetch and checkout docs branch
        run: |
          git fetch origin
          git checkout docs

      - name: Copy lab files from main to docs
        run: |
          # Sync lab files from the root directory
          git checkout main -- lab1/ lab3/ lab5/ lab6/ lab7/ # Add as many lab directories as needed
          git checkout main -- *.md *.ipynb # Sync root-level .txt files or other specific files

          # Remove unwanted files like .gitignore, README.md
          git rm .gitignore || true  # Remove .gitignore if it was merged
          git rm README.md || true   # Remove README.md if it was merged


      - name: Restore docs-specific files to ensure they are not overwritten
        run: |
          git restore --source=docs .github/workflows/ci.yml
          git restore --source=docs mkdocs.yml
          git restore --source=docs docs/

      - name: Commit and push changes to docs
        run: |
          git commit -m "Sync lab files from main to docs"
          git push origin docs
