name: Sync Docs on Main Update

on:
  push:
    branches:
      - main  # Trigger only when there's a push to the main branch

permissions:
  contents: write

jobs:
  sync_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git credentials for pushing to docs branch
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Merge main branch into docs
        run: |
          git fetch origin
          git checkout docs
          
          # Merge main into docs, allow unrelated histories
          git merge origin/main --allow-unrelated-histories --no-edit || true

          # Prevent overwriting the ci.yml in the docs branch
          git restore --source=docs .github/workflows/ci.yml

          # Check for any conflicts, exit if found
          if git ls-files -u | grep -q "."; then
            echo "There are still unresolved conflicts"
            exit 1
          fi

          git commit -m "Sync main branch files into docs branch without overwriting ci.yml in docs"

      - name: Push changes to docs branch
        run: git push origin docs
